### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by binaryfire** [abrahamgreyson/cache-for-laravel-sanctum#11]
Hey Abraham

Unless I'm mistaken there's a pretty big security issue with the findToken() method. Once the cache is set, tokens are only checked against the id. Which means anyone can just pass in a token id and if there's a match, they'll be authenticated.

You can reproduce this by authenticating with a token from Postman then changing the value of the Bearer token. As long as the id at the start is the same, you'll be able to successfully make requests.

**Comment by abrahamgreyson** [comment]
thank you for your noticed, i will check this later
    	获取 Outlook for iOS
    
  

 发件人: ***@***.*** ***@***.***> 代表 Raj Siva-Rajah ***@***.***>发送时间: 星期四, 四月 13, 2023 10:52 下午收件人: cache-for-laravel-sanctum ***@***.***>抄送: subscribed ***@***.***>主题: [abrahamgreyson/cache-for-laravel-sanctum] Security issue (Issue #11) 
Hey Abraham
Unless I'm mistaken there's a pretty big security issue with the findToken() method. Once the cache is set, tokens are only checked against the id. Which means anyone can just pass in a token id and if there's a match, they'll be authenticated.
You can reproduce this by authenticating with a token from Postman then changing the value of the Bearer token. As long as the id at the start is the same, you'll be able to successfully make requests.

**Comment by abrahamgreyson** [comment]
Thank you for your noticed, I will go through this later.
    	获取 Outlook for iOS
    
  

 发件人: ***@***.*** ***@***.***> 代表 Raj Siva-Rajah ***@***.***>发送时间: 星期四, 四月 13, 2023 10:52 下午收件人: cache-for-laravel-sanctum ***@***.***>抄送: subscribed ***@***.***>主题: [abrahamgreyson/cache-for-laravel-sanctum] Security issue (Issue #11) 
Hey Abraham
Unless I'm mistaken there's a pretty big security issue with the findToken() method. Once the cache is set, tokens are only checked against the id. Which means anyone can just pass in a token id and if there's a match, they'll be authenticated.
You can reproduce this by authenticating with a token from Postman then changing the value of the Bearer token. As long as the id at the start is the same, you'll be able to successfully make requests.

**Comment by rodrigocabraln** [comment]
Please fix this, it's a serious problem
